### ISSUE TITLE
The maps from your cycling trip are broken

### ISSUE THREAD

**Issue by 0xtobit** [JStech/jstech.github.io#1]
At the top the following is diplayed

> Some custom on-map content could not be displayed.

It links to this page [KML content isn't available in Google Maps](https://support.google.com/maps/answer/41136?p=kml&hl=en&rd=1)

**Comment by JStech** [comment]
I finally looked into this today. I've started fixing it, but it's going to take a while. Thanks for the report.

**Comment by 0xtobit** [comment]
Cool deal!

**Comment by JStech** [comment]
Done.

**Comment by 0xtobit** [comment]
Confirmed. Works on my machine!
